version: "2"
services:
  react:
    build: ./docker/react
    command: yarn start
    environment:
      - PORT=8000
    volumes:
      - ./react:/app
      - node-modules:/app/node_modules
    ports:
      - "8000:8000"
volumes:
  node-modules:
